project:
  type: book
  output-dir: docs

book:
  title: "GVCode Trainee"
  author: "GVCode"
  favicon: assets/icon.png
  sidebar:
    logo: assets/icon.png
  chapters:
    - index.qmd
    - aula1-python1.ipynb
    - aula2-python2.ipynb
    - aula3-python3.ipynb
    - aula4-cd-manipulacao.ipynb
    - aula5-cd-visualizacao.ipynb
    - aula6-cd-modelagem.ipynb
    - aula7-cd-projetos.ipynb
    - aula8-outros.ipynb
    - references.qmd

bibliography: assets/references.bib

format:
  html:
    theme: pulse
# Other themes: quartz, vapor
