project:
  type: book
  output-dir: docs

book:
  title: "GVCode Trainee"
  author: "GVCode"
  favicon: assets/icon.png
  description: Livro Quarto do curso de trainee da GVCode
  site-url: https://gvcode.github.io/trainee/
  repo-url: https://github.com/gvcode/trainee
  repo-branch: main
  sidebar:
    logo: assets/icon.png
  chapters:
    - index.qmd
    - aula1-python1.ipynb
    - aula2-python2.ipynb
    - aula3-python3.ipynb
    #- aula4-cd-manipulacao.ipynb
    #- aula5-cd-visualizacao.ipynb
    #- aula6-cd-modelagem.ipynb
    #- aula7-cd-projetos.ipynb
    #- aula8-outros.ipynb
    #- references.qmd

bibliography: assets/references.bib

format:
  html:
    theme: pulse # Other themes: quartz, vapor
    code-link: true
    css: assets/style.css

execute:
  cache: true

#filters:
#  - assets/view_html_comments.lua
# deixar visível os comentários para professores. Renderizar o livro sem isso quando o trainee começar
