# Bem Vindos! {.unnumbered}

Este é o material do curso de Trainee da GVCode. Cada capítulo está associado a uma aula presencial.

Esse material foi 100% escrito pelos veteranos da entidade, e está sendo otimizado desde 2020! Ao final, temos algumas das bibliografias utilizadas em sua confecção.

## Aulas

**Introdução ao Python I (30/set a 4/out)**

- O que é um script; sintaxe; variáveis; tipos de dados.
- Operadores; control flow; funções.
- Extra: *args; condições (try except).

**Introdução ao Python II (7/out a 11/out)**

- Programação orientada ao objeto.
- Coleções (list, dict, tuple, set); subsetting e métodos.
- Iteráveis loops, comprehension, e enumerate, filter, zip, e map.
- Extra: funções úteis, f-strings

**Introdução ao Python III (14/out a 18/out)**

- Numpy: arrays e vetorização; operações e subsetting.
- Pandas: dataframes; operações.
- Extra: tópicos avançados em Numpy e Pandas.

**Ciência de Dados: Manipulação (21/out a 25/out)**

- Introdução à ciência de dados; o que é processamento de dados.
- Como arrumar dados com Pandas.

**Ciência de Dados: Visualização (28/out a 1/nov)**

- O que é visualização de dados.
- Sumarização com Pandas; Gráficos com o Matplotlib.
- Extra: seaborn e outras bibliotecas; gráficos avançados.

**Ciência de Dados: Modelagem  (4/nov a 8/nov)**

- O que é modelagem de dados.
- Aula teórica sobre modelos de machine learning.

**Ciência de Dados: Projetos (11/nov a 15/nov)**

- Etapas e exemplo de um script de ciência de dados.
- Funções de modelagem.
- Extra: apresentar trabalho.

**Outros Temas em Programação (18/nov a 22/nov)**

- Git e Github.
- Boas práticas de programação (python’s pep8).
- Extra: regex; web scrapping.
